### ISSUE TITLE
MovieAppWidgetTest Failing

### ISSUE THREAD

**Issue by felangel** [salihgueler/flutter-popular-movies#2]
`══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): A typed argument was passed in as a named argument named "Symbol("onError")",
but did not pass a value for `named`. Each typed argument that is passed as a named argument needs
to specify the `named` argument. For example: `when(obj.fn(x: typed(any, named: "x")))`.

When the exception was thrown, this was the stack:
#0      _InvocationForTypedArguments._reconstituteNamedArgs.<anonymous closure> (package:mockito/src/mock.dart:211:11)
#1      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#2      MapView.forEach (dart:collection/maps.dart:339:10)
#3      _InvocationForTypedArguments._reconstituteNamedArgs (package:mockito/src/mock.dart:206:31)
#4      new _InvocationForTypedArguments (package:mockito/src/mock.dart:179:26)
#5      _useTypedInvocationIfSet (package:mockito/src/mock.dart:148:22)
#6      Mock.noSuchMethod (package:mockito/src/mock.dart:105:18)
#7      MockHttpClientResponse.listen ()
#8      createMockImageHttpClient (file:///Users/qtb9604/Downloads/flutter-popular-movies-FPM-Testing/test/MockImageHttpClient.dart:25:17)
#9      _HttpOverridesScope.createHttpClient (dart:_http/overrides.dart:103:43)
#10     new HttpClient (dart:_http:1371:22)
#11     NetworkImage._httpClient (package:flutter/src/painting/image_provider.dart:434:45)
#12     NetworkImage._httpClient (package:flutter/src/painting/image_provider.dart:434:27)
#13     NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:440:45)
<asynchronous suspension>
#14     NetworkImage.load (package:flutter/src/painting/image_provider.dart:425:14)
#15     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
#16     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
#17     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:63)
#18     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
#19     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:263:30)
#20     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:526:20)
#21     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:501:5)
#22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3767:12)
#23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
#26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
#37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
#38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
#39     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
#49     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
#50     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
#51     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
#52     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
#53     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
#54     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
#55     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
#56     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
#57     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
#58     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:321:5)
#59     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#61     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#63     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:336:13)
#64     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1172:12)
#65     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1090:20)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#83     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
#84     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
#85     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
#86     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#88     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#90     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#91     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#95     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#97     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#99     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#101    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#103    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#105    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#107    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#108    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#110    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#112    __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#113    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#114    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#115    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#116    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#118    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#120    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#121    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#122    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#123    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#124    RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
#125    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
#126    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
#127    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:732:23)
#128    _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#129    _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#130    _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#131    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:648:9)
#134    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#135    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:636:27)
#136    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:219:22)
#139    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#140    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:216:27)
#141    main.<anonymous closure>.<anonymous closure> (file:///Users/qtb9604/Downloads/flutter-popular-movies-FPM-Testing/test/MovieAppWidgetTest.dart:32:20)
<asynchronous suspension>
#145    HttpOverrides.runZoned (dart:_http/overrides.dart:57:26)
#146    main.<anonymous closure> (file:///Users/qtb9604/Downloads/flutter-popular-movies-FPM-Testing/test/MovieAppWidgetTest.dart:31:19)
<asynchronous suspension>
#147    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:65:23)
#148    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:502:19)
<asynchronous suspension>
#151    TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:486:14)
#152    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:765:24)
#158    AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:763:16)
#159    testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:64:22)
#160    Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#161    Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#165    Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#166    Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#170    Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#171    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#185    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#186    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#187    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided 33 frames from class _FakeAsync, package dart:async, and package stack_trace)

Image provider: NetworkImage("https://image.tmdb.org/t/p/w500//nl79FQ8xWZkhL3rDr1v2RFFR6J0.jpg",
scale: 1.0)
Image key: NetworkImage("https://image.tmdb.org/t/p/w500//nl79FQ8xWZkhL3rDr1v2RFFR6J0.jpg", scale:
1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
`

**Comment by salihgueler** [comment]
Thanks for reporting it, I will be on to that 👍

**Comment by salihgueler** [comment]
It's fixed with the related PR.
